### ISSUE TITLE
Zoompan option fps not found

### ISSUE THREAD

**Issue by tnedev** [remko/kburns#2]
Hi, 
When I tried the script or the standalone full command I got this error:
[Parsed_zoompan_3 @ 0x2504060] Option 'fps' not found
[AVFilterGraph @ 0x24ff960] Error initializing filter 'zoompan' with args 'z=if(eq(on,1),1,zoom+0.000417):x=0:y=ih-ih/zoom:fps=60:d=60*4:s=1280x800'
Error initializing complex filters.
Option not found

Any ideas?

**Comment by snblackout** [comment]
To get around this, I just commented out the old line #211, copy/paste and removed the fps option from the updated command:

`#filters << "zoompan=z='#{z}':x='#{x}':y='#{y}':fps=#{options.fps}:d=#{options.fps}*#{options.slide_duration_s}:s=#{width}x#{height}"`

`filters << "zoompan=z='#{z}':x='#{x}':y='#{y}':d=#{options.fps}*#{options.slide_duration_s}:s=#{width}x#{height}"`

**Comment by remko** [comment]
Since the `fps` option is documented, this sounds like an old version of ffmpeg. It's probably too late to check now (I missed notifications), but in absence of the option, removing it as suggested by @snblackout would be a workaround.
